export default function Head() {
    return (
        <>
            {/* eslint-disable-next-line react/no-unescaped-entities */}
            <title>La la la Jamie's world, Jamie's world</title>
            <meta content="width=device-width, initial-scale=1" name="viewport"/>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </>
    )
}
